#!/usr/bin/env python3
"""One-off: merge Claude's scoring with posts.json -> data/review.json."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
posts = {p["idx"]: p for p in json.load(open(os.path.join(ROOT, "data/posts.json")))}

# Per-post scoring/drafting. Keyed by idx. Only real posts (ads/recommendations dropped).
S = {
 0: dict(author="Janis Strapcans", headline="Founder", reactions=6, comments=0,
    match_author="Janis Strapcans", match_text="Founders build companies. Mentors build founders",
    key="janis strapcans | founders build companies. mentors build founders",
    score=5, include=True, like=True,
    reason="Founder (Baltic/Nordic-adjacent), short gratitude/milestone post; light engagement for reach.",
    comment="Mentors building founders is underrated, the compounding shows up years later. Well put."),

 1: dict(author="Bridget Onyeije", headline="Healthcare Data Analyst | PharmD Candidate", reactions=7, comments=4,
    match_author="Bridget Onyeije", match_text="What I’d Track as a Healthcare BI Analyst",
    key="bridget onyeije | match fit metrics: what i'd track as a healthcare bi",
    score=4, include=False, like=False,
    reason="Substantive but off-theme (healthcare BI), outside ICP and regions; skip.",
    comment=""),

 2: dict(author="Forward Accelerator", headline="Startup accelerator", reactions=3, comments=2,
    match_author="Forward Accelerator", match_text="In the week 3 logs we reviewed, 9 teams reported",
    key="forward accelerator | in the week 3 logs we reviewed, 9 teams reported",
    score=5, include=True, like=True,
    reason="Startup/building theme, honest accelerator update; worth a comment for reach.",
    comment="The honest part is listing the team under internal pressure and the one that already pivoted in the same update, most accelerators only show the pilots. Week 3 is exactly when the real signal separates from the noise."),

 4: dict(author="Anna Bila", headline="COO @ nCube", reactions=32, comments=7,
    match_author="Anna Bila", match_text="have you shorted the AI companies yet",
    key="anna bila | so, have you shorted the ai companies yet",
    score=3, include=False, like=False,
    reason="One-line provocation, near-zero substance (hard-skip criterion).",
    comment=""),

 5: dict(author="ARCTIC15 - 15th Anniversary Edition", headline="Startup event (Helsinki)", reactions=9, comments=0,
    match_author="ARCTIC15", match_text="Welcome Our New Speakers",
    key="arctic15 | welcome our new speakers tuija kalpala ilari kinnunen",
    score=4, include=False, like=False,
    reason="Nordic ecosystem event but speaker-announcement, off ICP theme; skip.",
    comment=""),

 6: dict(author="Alistair Greenwood", headline="Founder OmniforceAI", reactions=15, comments=13,
    match_author="Alistair Greenwood", match_text="You've used Claude Code for months",
    key="alistair greenwood | you've used claude code for months",
    score=6, include=True, like=True,
    reason="Founder, dev-tools/AI theme (Claude Code); good engagement and on-theme audience.",
    comment="Skills being the biggest lever matches my experience, the slash command discovery is what finally made them stick for the team. Which one took you longest to actually fold into daily use?"),

 7: dict(author="Dr. Oliver Borchers", headline="AI That Ships | Ex-CTO (EUR 13M Series A)", reactions=4, comments=2,
    match_author="Oliver Borchers", match_text="AI labs have no path to profitability",
    key="dr. oliver borchers | ai labs have no path to profitability",
    score=6, include=True, like=True,
    reason="Ex-CTO (Germany), thoughtful AI-economics take; adjacent theme, sharp engagement.",
    comment="Most teams quietly price their business case at subsidised 2026 token rates and call it a margin. Stress testing at 2 to 3x is the only way to know if you built something real or just rented someone else's burn rate."),

 8: dict(author="Oscar Horn", headline="Building LinkedIn personal brands", reactions=62, comments=66,
    match_author="Oscar Horn", match_text="Working from home is great and all but the last weeks",
    key="oscar horn | working from home is great and all but the last weeks",
    score=4, include=False, like=False,
    reason="Personal remote-work post, high engagement but off ICP theme; skip.",
    comment=""),

 9: dict(author="Florian Seibel", headline="The Future is Unmanned", reactions=78, comments=6,
    match_author="Florian Seibel", match_text="There you have it",
    key="florian seibel | there you have it i knew i was right hardwareishard",
    score=3, include=False, like=False,
    reason="Founder but post has near-zero substance (platitude); skip.",
    comment=""),

 10: dict(author="Mayank Maurya", headline="Growth Hacker / Personal Brand Strategist", reactions=155, comments=45,
    match_author="Mayank Maurya", match_text="Be kind” sounded useless to me",
    key="mayank maurya | be kind sounded useless to me until my client led",
    score=3, include=False, like=False,
    reason="Engagement-bait formatting + generic leadership content, off ICP; skip.",
    comment=""),

 11: dict(author="Tzu Tai Huang", headline="Marketing & Sales Specialist", reactions=3, comments=1,
    match_author="Tzu Tai Huang", match_text="I'm ready for it",
    key="tzu tai huang | i'm ready for it arctic15",
    score=3, include=False, like=False,
    reason="Low-substance event hype; skip.",
    comment=""),

 12: dict(author="Riga TechGirls", headline="Tech community (Latvia)", reactions=33, comments=2,
    match_author="Riga TechGirls", match_text="sneak peak at the first pictures from the Riga TechGirls",
    key="riga techgirls | sneak peak at the first pictures from the riga techgirls",
    score=4, include=False, like=False,
    reason="Nordic-adjacent community event recap, off ICP theme; skip.",
    comment=""),

 13: dict(author="Anni Tapionlinna", headline="Visiting Associate at BCG | Aalto University", reactions=125, comments=14,
    match_author="Anni Tapionlinna", match_text="I didn’t expect my first hackathon to end like this",
    key="anni tapionlinna | i didn't expect my first hackathon to end like this",
    score=5, include=True, like=True,
    reason="Finland (top region), strong milestone (won quantum hackathon); short genuine congrats.",
    comment="Winning the overall plus a challenge on your first hackathon is a serious start. Quantum finance is no gentle place to begin either, congrats to the team."),

 14: dict(author="johannes kuusela", headline="M.Sc. Student, University of Turku", reactions=25, comments=4,
    match_author="johannes kuusela", match_text="completed my Bachelor's degree in Automation Engineering",
    key="johannes kuusela | happy to share that i have completed my bachelor's",
    score=4, include=False, like=False,
    reason="Finland milestone but low substance and student/non-ICP; skip to preserve volume for better fits.",
    comment=""),

 15: dict(author="Winnie Khoo", headline="Partner, Antler (Disrupt)", reactions=36, comments=2,
    match_author="Winnie Khoo", match_text="I have a bone to pick with one of our founders",
    key="winnie khoo | i have a bone to pick with one of our founders",
    score=4, include=False, like=False,
    reason="VC founder shout-out but uses 'comment JAMES' engagement-bait gimmick + Asia region; skip.",
    comment=""),

 16: dict(author="Aakash Gandhi", headline="Helping founders & agencies ship MVPs & AI automation", reactions=14, comments=2,
    match_author="Aakash Gandhi", match_text="A client tried to negotiate my rate down because",
    key="aakash gandhi | a client tried to negotiate my rate down because you're",
    score=6, include=True, like=True,
    reason="Builder/founder, AI + shipping software, sharp pricing-judgment take; good engagement.",
    comment="Charging for judgment instead of keystrokes is the whole argument, the clients pushing hardest on 'but AI' are usually the ones who'll pay 3x later to unwind the vibe coded version. Owning the 2am production break is not something a cheaper rate ever covers."),

 17: dict(author="Mercy Emeka", headline="Brand Strategist", reactions=519, comments=517,
    match_author="Mercy Emeka", match_text="I'm at 20,000 followers",
    key="mercy emeka | i'm at 20,000 followers. but i'm jealous of creators",
    score=4, include=False, like=False,
    reason="High engagement but off-theme creator/branding + engagement-bait close; skip.",
    comment=""),

 18: dict(author="Paul Westerlund", headline="AI Architect | Privacy-First AI & Local LLMs | Ex-CTO", reactions=2, comments=0,
    match_author="Paul Westerlund", match_text="ChatGPT vai Claude",
    key="paul westerlund | chatgpt vai claude miten ja mihin tarkoitukseen",
    score=6, include=True, like=True,
    reason="Finland (top region), 1st-degree, AI architect/ex-CTO; AI-tooling theme. Post is Finnish, comment in English.",
    comment="The split you're drawing makes sense: local models for the critical data, public ones for sparring and ideation. For coding specifically, have you found Claude consistently ahead, or does it depend on the language?"),

 19: dict(author="Apostolos Apostolou", headline="Autonomous Systems - DTU | Control Engineer at Siemens Energy", reactions=11, comments=2,
    match_author="Apostolos Apostolou", match_text="participate in the Mini Factory Copenhagen Hackathon",
    key="apostolos apostolou | this weekend, i had the opportunity to participate",
    score=5, include=True, like=True,
    reason="Denmark (top region), substantive robotics/VLA build; good technical engagement.",
    comment="Training VLA models on real demo data over a weekend is a serious pace, the sorting plus repair routing pipeline is a clean end to end test. How well did the LeRobot policies hold up on parts they hadn't seen in the demos?"),

 21: dict(author="Andreas Helland", headline="CEO & Co-Founder at Atender Group", reactions=7, comments=0,
    match_author="Andreas Helland", match_text="Why are there frying pans on your desk",
    key="andreas helland | why are there frying pans on your desk you might be",
    score=6, include=True, like=True,
    reason="Founder (Nordics), building an AI-first CX product; playful but real product post.",
    comment="The frying pan budget clearly paid off. Going BPO to AI first in support is the hard version of this, most stop at a chatbot bolted onto the old flow. What's been the trickiest part of the transition?"),

 22: dict(author="Marianne van Groeningen", headline="Founder & CEO Executive Career Coaching", reactions=27, comments=39,
    match_author="Marianne van Groeningen", match_text="3 provocations to become aware that AI will not make you obsolete",
    key="marianne van groeningen | every leader needs to be aware of these 3 provocations",
    score=6, include=True, like=True,
    reason="Founder (NL), AI governance / decision-authority framework; adjacent theme, strong engagement.",
    comment="The tiering is clean, the hard part is usually enforcing 'in writing' when the decision rights keep shifting under teams. How do you keep the matrix from going stale once agents start changing what tier 1 even means?"),

 23: dict(author="Clare Kitching", headline="AI & data strategy, governance | xQuantumBlack, xMcKinsey", reactions=64, comments=65,
    match_author="Clare Kitching", match_text="AI works best when it’s used like a knife, not a miracle",
    key="clare kitching | ai works best when it's used like a knife, not a miracle",
    score=7, include=True, like=True,
    reason="AI strategy advisor (works across clients, UK), high-engagement substantive post; strong target.",
    comment="The scatter usually isn't a strategy failure, it's that nobody redesigns the workflow around the tool, so it sits next to the old process. Curious where you see teams lose focus most, picking the use cases or sustaining them once the first one works?"),

 24: dict(author="Melissa Rosenthal", headline="Co-Founder @ Outlever | Ex CCO ClickUp, VP Creative BuzzFeed", reactions=111, comments=58,
    match_author="Melissa Rosenthal", match_text="The New York Times just declared LinkedIn is entering its",
    key="melissa rosenthal | the new york times just declared linkedin is entering",
    score=6, include=True, like=True,
    reason="Founder (US), high-engagement sharp brand/media take; good for reach.",
    comment="Boring was the strategy is the sharp bit here, the real name attached is the entire trust premium and entertainment quietly erodes it. The moment people optimise for reach, the authenticity they're performing starts to read as the opposite."),

 25: dict(author="Asad Najeeb", headline="SEO Consultant", reactions=11, comments=14,
    match_author="Asad Najeeb", match_text="A lot of people still think great content is about storytelling first",
    key="asad najeeb | a lot of people still think great content is about storytelling",
    score=5, include=False, like=False,
    reason="SEO/AI-retrieval content, substantive but lower regional/ICP fit; trimmed to keep ~20 best includes.",
    comment=""),

 26: dict(author="BUSOLA HELEN AWOTIMIDE", headline="DevOps & Cloud Engineer", reactions=365, comments=592,
    match_author="BUSOLA HELEN AWOTIMIDE", match_text="We hit 5,000 followers",
    key="busola helen awotimide | we hit 5,000 followers thank you for every like",
    score=3, include=False, like=False,
    reason="Pure follower-count milestone, low substance, off region; skip.",
    comment=""),

 27: dict(author="Oloketuyi Opeyemi", headline="Digital Marketer", reactions=1, comments=0,
    match_author="Oloketuyi Opeyemi", match_text="My uncle served in Benue before me",
    key="oloketuyi opeyemi | my uncle served in benue before me",
    score=2, include=False, like=False,
    reason="Personal anecdote, off-theme and off-region; skip.",
    comment=""),

 28: dict(author="Adrian Yijie Xu, PhD", headline="Accelerating LifeScience @ AMD SiloAI", reactions=1, comments=0,
    match_author="Adrian Yijie Xu", match_text="great to attend #RECOMB2026 this year, our first as a gold-tier sponsor",
    key="adrian yijie xu | was great to attend recomb2026 this year, our first as a",
    score=5, include=True, like=True,
    reason="AMD Silo AI (Finland), substantive AI/compute-bio recap, 1st-degree; adjacent AI theme.",
    comment="The shift toward pretrained bio foundation models as general purpose representations is the throughline across all four drivers you listed. Reliability getting its own bucket is telling, calibration and uncertainty are where most of these models still quietly fail."),

 29: dict(author="Michael Oyewusi", headline="Senior Product Designer | Design Educator | Founder", reactions=82, comments=44,
    match_author="Michael Oyewusi", match_text="Your beautiful Figma Resume might be costing you interviews",
    key="michael oyewusi | your beautiful figma resume might be costing you interviews",
    score=6, include=True, like=True,
    reason="Product Designer + Founder, design/Figma theme (ICP author), high engagement.",
    comment="Wild that the same craft that makes a portfolio shine is exactly what the ATS chokes on. How do you tell designers to handle that tension without flattening their visual identity entirely?"),

 30: dict(author="Shahid Reza", headline="Founder of ToolmetryAI", reactions=1, comments=0,
    match_author="Shahid Reza", match_text="Working with APIs becomes frustrating when JSON is messy",
    key="shahid reza | working with apis becomes frustrating when json is messy",
    score=4, include=False, like=False,
    reason="Self-promotion of own tool (hard-skip leaning); skip.",
    comment=""),

 31: dict(author="Jogosoft Information Technology", headline="IT/SEO company", reactions=26, comments=46,
    match_author="Jogosoft", match_text="Most businesses don't have a content problem",
    key="jogosoft information technology | most businesses don't have a content problem",
    score=4, include=False, like=False,
    reason="Company SEO content, off core theme; skip.",
    comment=""),

 32: dict(author="Elina Lappalainen", headline="Business Journalist, Helsingin Sanomat Visio", reactions=6, comments=1,
    match_author="Elina Lappalainen", match_text="Kerrostalo keskellä järvimaisemaa",
    key="elina lappalainen | kerrostalo keskella jarvimaisemaa ja huvilahistoriaa",
    score=3, include=False, like=False,
    reason="Finnish-language personal post about her apartment building; off-theme; skip.",
    comment=""),

 33: dict(author="James Easterbrook", headline="Customer Services Manager @ Ark-H Handling", reactions=271, comments=331,
    match_author="James Easterbrook", match_text="my content has had over half a MILLION impressions",
    key="james easterbrook | excited to share that in the last 7 days my content",
    score=3, include=False, like=False,
    reason="Impressions-milestone, low substance, off ICP; skip.",
    comment=""),

 34: dict(author="Cadmatic", headline="Engineering/design software (Finland)", reactions=2, comments=0,
    match_author="Cadmatic", match_text="standout sessions at Cadmatic Digital Wave Forum",
    key="cadmatic | what made the standout sessions at cadmatic digital wave forum",
    score=5, include=True, like=True,
    reason="Finland, design/engineering workflows + information management; adjacent theme worth warming.",
    comment="Model connected progress tracking on a live plant project sounds incremental until you've watched teams lose weeks to stale drawings. How much of the win came from the tooling versus getting teams to actually trust one source?"),

 35: dict(author="Kelvin Osei", headline="Content strategist", reactions=16, comments=12,
    match_author="Kelvin Osei", match_text="We are hiring",
    key="kelvin osei | we are hiring new week new opportunities remotown",
    score=0, include=False, like=False,
    reason="Hiring post (hard skip).",
    comment=""),

 36: dict(author="Muhammad Imran Asghar", headline="Associate Professor, Tampere University", reactions=19, comments=1,
    match_author="Muhammad Imran Asghar", match_text="attending ARCTIC15 - 15th Anniversary Edition",
    key="muhammad imran asghar | i am attending arctic15 representing smart+ions",
    score=4, include=False, like=False,
    reason="Finland academic, but energy/hardware deeptech off ICP theme + event-attendance; skip.",
    comment=""),

 37: dict(author="Jonathan Otafia", headline="LinkedIn Visibility System", reactions=307, comments=412,
    match_author="Jonathan Otafia", match_text="I moved from 3k → 5K+ profile views on LinkedIn using this ILLEGAL move",
    key="jonathan otafia | in 7 days, i moved from 3k to 5k+ profile views",
    score=3, include=False, like=False,
    reason="Growth-hack engagement-bait + self-promo; skip.",
    comment=""),

 38: dict(author="Orfeuo Lionor", headline="Freelance Startup coach | innovation consultant | External evaluator", reactions=10, comments=0,
    match_author="Orfeuo Lionor", match_text="The six core -Ilities",
    key="orfeuo lionor | whether i'm coaching an early-stage startup, or a scaleup",
    score=6, include=True, like=True,
    reason="Fractional/innovation consultant across clients, useful venture framework; engagement target.",
    comment="The six Ilities holding up across early stage, scaleup and EU evaluation is a good signal the framework is real and not just a deck. Which one do founders most consistently underweight, defensibility?"),

 39: dict(author="Martha Oluchi Abonyi", headline="Digital Marketer | Personal Branding", reactions=196, comments=155,
    match_author="Martha Oluchi Abonyi", match_text="use what you have until you have more to use",
    key="martha oluchi abonyi | please, use what you have until you have more to use",
    score=3, include=False, like=False,
    reason="Personal/branding story, off ICP theme and region; skip.",
    comment=""),

 40: dict(author="Lebohang Makateng", headline="Software Developer", reactions=3, comments=0,
    match_author="Lebohang Makateng", match_text="built a Notion-Powered Memory System for my AI agent",
    key="lebohang makateng | i built a notion-powered memory system for my ai agent",
    score=7, include=True, like=True,
    reason="Directly on-theme: AI-with-no-context / context fragmentation pain (memory system, stale context). Pain match.",
    pain_match=True, pain_tags=["context-fragmentation"],
    prospect_tier="warm", prospect_persona="solo-builder", pain_magnitude=3,
    comment="The 'context goes stale the moment I change something in Notion' problem is the real one, caching buys speed but staleness creeps right back. How are you handling invalidation when a page changes, polling or webhooks?"),

 41: dict(author="Muhammad Usman Shahbaz", headline="AI | Data | Python | AWS | Azure", reactions=104, comments=45,
    match_author="Muhammad Usman Shahbaz", match_text="7 RAG Design Patterns You Must Know in 2026",
    key="muhammad usman shahbaz | 7 rag design patterns you must know in 2026",
    score=6, include=True, like=True,
    reason="High-engagement AI/RAG (retrieval-context) post; adjacent to 'AI with no context' theme.",
    comment="Agentic RAG is where most teams jump too early, the router only helps once retrieval quality on the naive version is actually solid. Are you seeing GraphRAG earn its complexity in production yet?"),

 42: dict(author="Abdulla Al Qubaisi", headline="Senior Director @ Dubai Holding Real Estate", reactions=75, comments=15,
    match_author="Abdulla Al Qubaisi", match_text="Growth is important, but so is appreciating where you are today",
    key="abdulla al qubaisi | growth is important, but so is appreciating where you are",
    score=2, include=False, like=False,
    reason="Two-line platitude, no substance; skip.",
    comment=""),

 43: dict(author="Paul Shoffner", headline="Creative Arts, Curator Of Quotes", reactions=0, comments=0,
    match_author="Paul Shoffner", match_text="The Ukrainians are now absorbing and carrying out",
    key="paul shoffner | the ukrainians are now absorbing and carrying out the entirety",
    score=0, include=False, like=False,
    reason="Politics/war (hard skip).",
    comment=""),

 44: dict(author="Kamena Taura", headline="Executive Search & Candidate Assessment", reactions=3, comments=0,
    match_author="Kamena Taura", match_text="TOP 3 vacancies this week",
    key="kamena taura | top 3 vacancies this week",
    score=0, include=False, like=False,
    reason="Recruitment/jobs post (hard skip).",
    comment=""),

 45: dict(author="Indie Stowell", headline="Freelance Social Media Marketer | Founder of The Marketing Lab", reactions=15, comments=10,
    match_author="Indie Stowell", match_text="role of the week is back",
    key="indie stowell | role of the week is back and this one is personal to me",
    score=5, include=True, like=True,
    reason="Founder (UK), marketing/content theme, substantive take on the content-marketer role.",
    comment="The gap between the 'content marketer' title and the actual job description is brutal, it's really five roles bundled into one rate. Do you think the people thriving in it are the ones who quietly refuse to do all five?"),

 46: dict(author="Ibironke O Semowo", headline="Mindful Parenting Coach", reactions=29, comments=37,
    match_author="Ibironke O Semowo", match_text="raising a well-behaved child and raising a confident one",
    key="ibironke o semowo | nobody told me that raising a well-behaved child and raising",
    score=2, include=False, like=False,
    reason="Parenting content, off-theme; skip.",
    comment=""),

 47: dict(author="Goodness Ifeaka", headline="Executive Virtual Assistant", reactions=58, comments=83,
    match_author="Goodness Ifeaka", match_text="3,000+ people are following this page now",
    key="goodness ifeaka | 3,000+ people are following this page now",
    score=3, include=False, like=False,
    reason="Follower-count milestone, off ICP theme/region; skip.",
    comment=""),

 48: dict(author="Babatunde James", headline="Premium LinkedIn Ghostwriter", reactions=148, comments=90,
    match_author="Babatunde James", match_text="The LINKEDIN hack that 10x my growth",
    key="babatunde james | the linkedin hack that 10x my growth without paying anyone",
    score=3, include=False, like=False,
    reason="LinkedIn growth-hack/self-promo; skip.",
    comment=""),

 49: dict(author="Tino Aliye", headline="Award-winning Founder @Tinova | brands for early-stage startups", reactions=56, comments=26,
    match_author="Tino Aliye", match_text="I bought a book called The Art of Managing Up",
    key="tino aliye | around february, i bought a book called the art of managing up",
    score=5, include=True, like=True,
    reason="Founder (brand agency for startups), substantive leadership take; good engagement.",
    comment="Managing up reframed as a leadership skill from the bottom is the useful flip, most people read it as just sending more status updates. The trust comes from bringing problems early, not from polishing the updates."),
}

out = []
for idx, s in S.items():
    p = posts.get(idx, {})
    out.append({
        "key": s["key"],
        "author": s["author"],
        "headline": s["headline"],
        "text": p.get("text", ""),
        "reactions": s.get("reactions", 0),
        "comments": s.get("comments", 0),
        "match_author": s["match_author"],
        "match_text": s["match_text"],
        "permalink": "",
        "author_profile": p.get("author_profile", ""),
        "pain_match": s.get("pain_match", False),
        "pain_tags": s.get("pain_tags", []),
        "prospect_tier": s.get("prospect_tier"),
        "prospect_persona": s.get("prospect_persona"),
        "pain_magnitude": s.get("pain_magnitude"),
        "score": s["score"],
        "reason": s["reason"],
        "comment": s["comment"],
        "include": s["include"],
        "like": s["like"],
        "follow": False,
    })

out.sort(key=lambda x: x["score"], reverse=True)
path = os.path.join(ROOT, "data/review.json")
json.dump(out, open(path, "w"), indent=2, ensure_ascii=False)
inc = sum(1 for x in out if x["include"])
print(f"Wrote {len(out)} entries -> {path}; {inc} included; {sum(1 for x in out if x['pain_match'])} pain_match")
